# --- Stage 1: Builder ---
FROM golang:1.23-alpine AS builder

# Set necessary environment variables
ENV CGO_ENABLED=0
ENV GOOS=linux

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum to cache dependencies
COPY go.mod go.sum ./
# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the Go application
# The -a flag forces a rebuild of packages that are already up-to-date
# The -installsuffix is often used with CGO_ENABLED=0 for static linking
RUN go build -ldflags "-s -w" -o main ./cmd/

# --- Stage 2: Final minimal image ---
FROM alpine:latest

# Set the working directory
WORKDIR /root/

# Copy the compiled binary from the builder stage
COPY --from=builder /app/main .
COPY --from=builder /app/ui ./ui

# Define the entrypoint to run the compiled application
CMD ["./main"]